FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
RUN pip install --no-cache-dir pyModbusTCP

WORKDIR /app
COPY modbus_server.py /app/modbus_server.py

EXPOSE 502
CMD ["python", "/app/modbus_server.py"]

